name: khedmaty_store
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  #  syncfusion_flutter_charts: ^22.2.9
#  syncfusion_flutter_charts:
  flutter_svg: ^2.0.5  # svg image
#  flutter_pw_validator: ^1.6.0
  easy_localization: ^3.0.1  # localization
  shared_preferences: ^2.1.1   # shared_preferences
  flutter_staggered_animations: ^1.1.1 # #animation
#  flutter_spinkit: ^5.1.0 #loading
  cached_network_image: ^3.2.2
#  awesome_dialog: ^3.0.2 #dialog
#  font_awesome_flutter: ^10.2.1
  #  dropdown_button2: ^2.3.9
  dropdown_button2:
#  photo_view: ^0.14.0

  #  rate_my_app: ^1.1.3
  #  audioplayers: ^1.1.1
#  password_field_validator: ^0.0.1
#  flutter_timer_countdown: ^1.0.5
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  image_picker: ^0.8.5
  url_launcher: ^6.0.20
  #log
  logger: ^1.1.0
  logging: ^1.1.0
  # State management
  provider: ^6.0.4
  lottie: #lottie
  country_code_picker: ^2.0.2  #country_code
  # DI
  get_it: ^7.2.0
#  equatable: ^2.0.5
  # smooth_page_indicator
  smooth_page_indicator: ^1.1.0
  # Network
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  shimmer: ^2.0.0
  fluttertoast: ^8.2.1
  google_maps_flutter: ^2.2.6
  # for place id
  geolocator: ^9.0.2
  geocoding: ^2.0.0
#  http: ^0.13.4
  # for map permission
  permission_handler: ^10.2.0
  # for notifications
#  firebase_auth: ^4.10.0
  flutter_rating_bar: ^4.0.1
#  firebase_core: ^2.7.0
#  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  #  flutter_html:
#  fdottedline_nullsafety: ^2.0.1


dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet



dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "https://sulah.sa/storage/images/admins/settings/wZdOQdpOpp1704022549.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "https://sulah.sa/storage/images/admins/settings/wZdOQdpOpp1704022549.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "/Users/Monem/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/gif/
    - assets/strings/
    - assets/lolitJson/


  fonts:
    - family: Madani Arabic Regular.ttf
      fonts:
        - asset: assets/fonts/Madani Arabic Regular.ttf
          weight: 400
    - family: Madani Arabic Semi Bold.ttf
      fonts:
        - asset: assets/fonts/Madani Arabic Semi Bold.ttf
          weight: 400

